production pipeline files
ZuckermanBrain/datajoint-costa pull request #95
Opened 2020-10-15 21:47 UTC by AliceCMos

2020-10-19 20:05 UTC, shenshan requested changes
Great work folks. I left some comments on the design consideration of a few tables, common patterns of dj and python usage and some minor details.

2020-10-19 20:05 UTC, shenshan commented on costa_pipeline_production/criteria.py
> +    """
The make function of this table heavily rely on `ScaraCriteriaParameters` and `scara.ScaraPerformance`. I would suggest to put some dependencies in the table definition. If `scara.ScaraPerformance` is not populated, `ScaraCriteria` should not be able to populate.

2020-10-20 18:38 UTC, shenshan commented on costa_pipeline_production/criteria.py
> +
key_source = scara.ScaraPerformance & ScaraCriteriaParameters
----
-> ScaraCriteriaParameters
-> scara.ScaraPerformance

2020-10-20 18:40 UTC, shenshan commented on costa_pipeline_production/criteria.py
> +    key_source = acquisition.Session & acquisition.Session.Scara
could be deleted

2020-10-20 18:50 UTC, shenshan commented on costa_pipeline_production/instrument.py
> +    opto_id:   varchar(64) # e.g. Driver number?
rename to something like `opto_setup_name`

2020-10-20 18:51 UTC, shenshan commented on costa_pipeline_production/lab.py
> +
remove the room numbers

2020-10-20 18:53 UTC, shenshan commented on costa_pipeline_production/opto_stimulus_scara.py
> +key_source = acquisition.Session & acquisition.Session.Optogenetics
could be removed

2020-10-20 18:55 UTC, shenshan commented on costa_pipeline_production/scara.py
> +
```
phase_row = {
'Phase 1' : 13,
'Phase 2' : 18,
'Phase 3' : 19
}
data = pd.read_csv(task_file_fullpath, sep=",", nrows=phase_row[phase], error_bad_lines=False, warn_bad_lines=False)
```

2020-10-20 18:58 UTC, shenshan commented on costa_pipeline_production/suite2p.py
> +        if len(result_script) > 1: #only populate if it ran
`if len(result_script):`

2020-10-20 19:00 UTC, shenshan commented on costa_pipeline_production/suite2p.py
> +    run_date=CURRENT_TIMESTAMP:  datetime
-> Suite2pParameters

2020-10-20 19:02 UTC, shenshan commented on costa_pipeline_production/twophoton.py
> +            raw_file_name = str(subject_id) + '_' + str(session_date.date()) + '_0001' +'.raw'
''.format()

2020-10-22 18:19 UTC, AliceCMos commented on costa_pipeline_production/twophoton.py
> +            if current_os == "Darwin":
yes, at the moment only scara experiments are run on this microscope. But will make it more general

2020-10-23 22:09 UTC, merged